### ISSUE TITLE
🐛[Bug]: 401 unauthorized

### ISSUE THREAD

**Issue by kierenblack** [biznisbox/biznisbox#104]
### What happened?

When i log in or try to open pages, I get an error saying
Your session has timed out. Please log in again.
I can only view the dashboard

### Version

1.10.1

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patik123** [comment]
Hello,
thank you for your report. But are there any logs on the server? 

Best. Patrick

**Comment by kierenblack** [comment]
Unfortunatly no. Laravel logs are not showing anything and neither are the nginx error logs.
The access logs show,
```
x.x.x.x - - [20/Mar/2024:19:42:17 +1300] "GET /api/admin/dashboard HTTP/2.0" 401 48 "https://invoice.xxx.nz/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
x.x.x.x - - [20/Mar/2024:19:42:17 +1300] "GET /api/dashboard HTTP/2.0" 401 48 "https://invoice.xxx.nz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

**Comment by patik123** [comment]
I think the problem is that the user does not have all access rights set.

But I don't know why it wouldn't work, since the rights were set at initialization for the admin role.

**Comment by kierenblack** [comment]
If you let me know what is meant to be in the database I can grab the data
from the relevant tables

**Comment by patik123** [comment]
The new version of the program is coming in the next few weeks I think your problem will be resolved.
