### ISSUE TITLE
Automatic Session has Timeout 

### ISSUE THREAD

**Issue by hrdgoriya** [biznisbox/biznisbox#31]
### What happened?

HI buddy,

I am facing issue with Session Timeout after successfully login, I have tried to host this application in Linux and Windows as well but the result is same,
After the Login, whenever i click on any module there is an error in right panel "Your session has timed out. Please log in again"

Database, PHP and Apache is installed as per requirements, and seems to be OK.

Also find atteched screeshot with error.

Please help to solved the issue.

![Login error](https://github.com/biznisbox/biznisbox/assets/129517251/f35e2297-5ed4-4331-8868-53f227eb2ad7)

### Relevant log output

```shell
#Please find below apache configuration 

<VirtualHost *:80>
     ServerAdmin youremail@localhost.com
     ServerName localhost.com
     ServerAlias www.localhost.com
     DocumentRoot "/var/www/invoice/public"
     <Directory /var/www/invoice/public>
         Options Indexes FollowSymLinks MultiViews
         AllowOverride All
         Order allow, deny
         allow from all
     </Directory>
</VirtualHost>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patik123** [comment]
Hello,
please check if you have a JWT token saved between cookies. A cookie is named a token and created after the login response on the client side.

**Comment by patik123** [comment]
Hello, 
have no idea why you get this error.

Please contact me at [patrick@biznisbox.com](mailto:patrick@biznisbox.com).
