### ISSUE TITLE
Unable to Login - After Successfully Installation

### ISSUE THREAD

**Issue by hrdgoriya** [biznisbox/biznisbox#9]
After entering correct credentials, Login but only blink nothing else, can you please help to resolved the issue, 
No error found in /var/log/apache2/error.log

**Comment by patik123** [comment]
Hello,
could you give me instructions on how did you install the app?

Maybe also a copy of the log in /storage/logs/laravel.log.

**Comment by hrdgoriya** [comment]
Hello,
I have follow same process for installation in given below link,
https://docs.biznisbox.com/docs/getting-started/installation/#creating-the-first-user

Please find version details,

root@test:~#php -v
PHP 8.2.8 (cli) (built: Jul 16 2023 11:01:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies

root@test:~# mysql --version 
mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

root@test:~# apache2 -v
Server version: Apache/2.4.52 (Debian)
Server built:   2022-02-08T05:32:10

Please find below apache config

root@test:~# cat /etc/apache2/sites-available/000-default.conf 
<VirtualHost *:80>

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html/invoice/public


Please find previous log of /var/www/html/invoice/storage/logs/laravel.log

#31 /var/www/html/invoice/vendor/laravel/framework/src/Illuminate/Console/Command.php(208): Illuminate\\Container\\Container->call()
#32 /var/www/html/invoice/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#33 /var/www/html/invoice/vendor/laravel/framework/src/Illuminate/Console/Command.php(177): Symfony\\Component\\Console\\Command\\Command->run()
#34 /var/www/html/invoice/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#35 /var/www/html/invoice/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /var/www/html/invoice/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#37 /var/www/html/invoice/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(200): Symfony\\Component\\Console\\Application->run()
#38 /var/www/html/invoice/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#39 {main}
"} 





^C
root@test:~# 

Logs are not generated during sign-in process..

**Comment by patik123** [comment]
Sorry, but I can't reproduce this issue.

**Comment by hrdgoriya** [comment]
Hello, Yes i am created, its might be past logs..

Please find below mysql details..

MariaDB [(none)]> SHOW GRANTS FOR 'invoice'@'localhost';
+----------------------------------------------------------------------------------------------------------------+
| Grants for invoice@localhost                                                                                   |
+----------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `invoice`@`localhost` IDENTIFIED BY PASSWORD '*D30107FB140FAB4366756509FD89F1469C0B36C0' |
| GRANT ALL PRIVILEGES ON `invoice`.* TO `invoice`@`localhost`                                                   |
+----------------------------------------------------------------------------------------------------------------+
2 rows in set (0.000 sec)

Database changed
MariaDB [invoice]> select * from users;
+--------------------------------------+-------------+-----------+------------------------+--------------------------------------------------------------+--------+---------+-------------+---------------+----------+------------+---------------------+---------------------+
| id                                   | first_name  | last_name | email                  | password                                                     | active | picture | role        | last_login_at | language | deleted_at | created_at          | updated_at          |
+--------------------------------------+-------------+-----------+------------------------+--------------------------------------------------------------+--------+---------+-------------+---------------+----------+------------+---------------------+---------------------+
| 99d1273a-112c-48e4-9fa3-262939904bf0 | Admin       | NULL      | admin@test.com         | $2y$10$9TikRg3NxtMSaO5wL0Sg4ujzCgrKI7ciPl2vNbBqUDWb1mQXw3GSK |      1 | NULL    | super_admin | NULL          | en       | NULL       | 2023-08-05 11:44:13 | 2023-08-05 11:44:13 |
+--------------------------------------+-------------+-----------+------------------------+--------------------------------------------------------------+--------+---------+-------------+---------------+----------+------------+---------------------+---------------------+
2 rows in set (0.001 sec)

Note : same details is saved to .env file..

Please also confirmed that below command should be execute before set .env file details ?
If yes - that was an error  "Database connection [] not configured."    
this is suggested by installation guide..

**Comment by hrdgoriya** [comment]
Can you please share the example of .env file and apache config file. ?

**Comment by patik123** [comment]
> Can you please share the example of .env file and apache config file. ?

Hello,
I can give you the .env file
```env
APP_NAME=BiznisBox
APP_ENV=dev
APP_KEY=base64:p+JmGnlVn+gC0mqguxPa2CKHYz64oGbKk5slYZkPd+U=
APP_DEBUG=true
APP_URL=http://localhost
JWT_KEY=1234567890
JWT_ALGO=HS256

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=biznisbox
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync

MAIL_MAILER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME="${APP_NAME}"
```

Can you get me the Chrome dev tools log? Because it is something wrong with the client side and screenshot of the app window.

**Comment by patik123** [comment]
Hello,
sorry for the late replay. 

According to the attached screenshot, I believe that there is an error in the configuration of the Apache server since the static content (JavaScript and CSS) is loaded correctly. Laravel framework used for API.

I would like to ask you to check the Apache server configuration.
Example server configuration:
```apache
<VirtualHost *:80>
     ServerAdmin youremail@domain.com
     ServerName yoursite.com
     ServerAlias www.yoursite.com
     DocumentRoot "/var/www/yoursite.com/public"
     <Directory /var/www/yoursite.com/public>
         Options Indexes FollowSymLinks MultiViews
         AllowOverride All
         Order allow, deny
         allow from all
     </Directory>
</VirtualHost>
```
I hope this will resolve your problem.

**Comment by hrdgoriya** [comment]
Thanks to resolve the Issue. 
I am appreciate your efforts.
